name: Node.js CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
      - uses: actions/setup-node@v4
        with:
          node-version-file: ".nvmrc"
          cache: "pnpm"
      - name: Install dependencies
        run: pnpm install
        env:
          CI: true
      - name: Install Playwright Browsers
        run: pnpm exec playwright install --with-deps
      - name: Run Lint
        run: pnpm lint
      - name: Run Typecheck
        run: pnpm typecheck
      - name: Run Unit Test
        run: pnpm unit
      - name: Run E2E Test
        run: pnpm integration
        env:
          GIF_API_KEY: ${{ secrets.GIF_API_KEY }}
